USE [master]
GO

/****** Object:  Database [INTEGRACAO]    Script Date: 09/19/2014 18:12:51 ******/
CREATE DATABASE [INTEGRACAO] ON  PRIMARY 
( NAME = N'INTEGRACAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\INTEGRACAO.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'INTEGRACAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\INTEGRACAO_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [INTEGRACAO] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INTEGRACAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ARITHABORT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [INTEGRACAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [INTEGRACAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [INTEGRACAO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [INTEGRACAO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [INTEGRACAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [INTEGRACAO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [INTEGRACAO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [INTEGRACAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [INTEGRACAO] SET  READ_WRITE 
GO

ALTER DATABASE [INTEGRACAO] SET RECOVERY FULL 
GO

ALTER DATABASE [INTEGRACAO] SET  MULTI_USER 
GO

ALTER DATABASE [INTEGRACAO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [INTEGRACAO] SET DB_CHAINING OFF 
GO



USE [INTEGRACAO]
GO
/****** Object:  User [integracao]    Script Date: 09/19/2014 14:03:58 ******/
CREATE USER [integracao] FOR LOGIN [integracao] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  StoredProcedure [dbo].[MANUFACTURING_BOM]    Script Date: 09/19/2014 14:03:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MANUFACTURING_BOM] (@order INT) AS


SELECT STUFF(
	(SELECT     
		',{"number":' + CAST(GPIMAC_Altamira.dbo.LPV.LPPED AS VARCHAR(MAX)) 
		+ ',"customer":"' + LTRIM(RTRIM(ISNULL(GPIMAC_Altamira.dbo.CACLI.CCNOM, ''))) + '"'
		+ ',"representative":"' + LTRIM(RTRIM(ISNULL(GPIMAC_Altamira.dbo.CAREP.CVNOM, ''))) + '"'
		+ ',"created":"' + LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR, GPIMAC_Altamira.dbo.LPV.LPENT, 127), ''))) /*'1410895028676'*/ + '"'
		+ ',"delivery":"' + LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR, GPIMAC_Altamira.dbo.LPV.LP0SAIRED, 127), ''))) /*'1410895028676'*/ + '"'
		+ ',"quotation":"' + GPIMAC_Altamira.dbo.LPV.LPWBCCADORCNUM + '"'
		+ ',"comment":"' + CASE WHEN LEN(LTRIM(RTRIM(GPIMAC_Altamira.dbo.LPV.LPObsOP))) = 0 THEN ' ' ELSE LTRIM(RTRIM(GPIMAC_Altamira.dbo.LPV.LPObsOP)) END + '"'
		+ ',"item":' + '[' + STUFF(
		(SELECT
			',{"item":' + CAST(ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.ORCITM, 0) AS VARCHAR(MAX)) 
			+ ',"description":"' + LTRIM(RTRIM(LEFT(ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.ORCTXT, ''), CHARINDEX(' Valor total líquido:', ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.ORCTXT, ''))))) + '"'
			--ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.ORCPRDQTD, 0) AS quantity, 
			--LTRIM(RTRIM(ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.ORCPRDCOD, ''))) AS code, 
			--ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.GRPCOD, 0) AS [group], 
			--ISNULL(WBCCAD.dbo.INTEGRACAO_ORCITM.SUBGRPCOD, 0) AS subgroup,
			+ ',"product":' + '[' + STUFF(
			(SELECT
				  --ISNULL([GRPCOD], 0) AS [group]
				  --,ISNULL([SUBGRPCOD], 0) AS subgroup
				  --,ISNULL([ORCITM], 0) AS item
				  ',{"code":"' + LTRIM(RTRIM(CASE WHEN CHARINDEX('#', ISNULL([PRDCOD], '')) > 0 THEN LEFT(ISNULL([PRDCOD], ''), CHARINDEX('#', [PRDCOD]) -1) ELSE ISNULL([PRDCOD], '') END)) + '"'
				  + ',"color":"' + LTRIM(RTRIM(ISNULL([CORCOD], ''))) + '"'
				  + ',"description":"' + LTRIM(RTRIM(ISNULL([PRDDSC], ''))) + '"'
				  + ',"quantity":' + CAST(CAST(ISNULL([ORCQTD], 0) AS DECIMAL(10,3)) AS NVARCHAR(MAX))
				  --,CAST(ISNULL([ORCTOT], 0) AS DECIMAL(10,3)) AS value,
				  + ',"weight":' + CAST(CAST(ISNULL([ORCPES], 0) AS DECIMAL(10,3)) AS NVARCHAR(MAX))
				  +'}'
			  FROM 
				[WBCCAD].[dbo].[INTEGRACAO_ORCPRD]
			  WHERE 
				[WBCCAD].[dbo].[INTEGRACAO_ORCPRD].ORCNUM = [WBCCAD].[dbo].[INTEGRACAO_ORCITM].ORCNUM AND
				[WBCCAD].[dbo].[INTEGRACAO_ORCPRD].ORCITM = [WBCCAD].[dbo].[INTEGRACAO_ORCITM].ORCITM
			  FOR XML PATH(''), TYPE).value('.', 'varchar(max)'), 1, 1, '') + ']' + '}'
		FROM 
			WBCCAD.dbo.INTEGRACAO_ORCCAB WITH (NOLOCK) INNER JOIN
			WBCCAD.dbo.INTEGRACAO_ORCITM WITH (NOLOCK) ON
			WBCCAD.dbo.INTEGRACAO_ORCCAB.ORCNUM = WBCCAD.dbo.INTEGRACAO_ORCITM.ORCNUM
		WHERE
			WBCCAD.dbo.INTEGRACAO_ORCCAB.ORCNUM = GPIMAC_Altamira.dbo.LPV.LPWBCCADORCNUM
		FOR XML PATH(''), TYPE).value('.', 'varchar(max)'), 1, 1, '') + ']' + '}'
	FROM         
		GPIMAC_Altamira.dbo.LPV WITH (NOLOCK) INNER JOIN
		GPIMAC_Altamira.dbo.CACLI WITH (NOLOCK) ON GPIMAC_Altamira.dbo.CACLI.CCCGC = GPIMAC_Altamira.dbo.LPV.CCCGC INNER JOIN
		GPIMAC_Altamira.dbo.CAREP WITH (NOLOCK) ON GPIMAC_Altamira.dbo.CAREP.CVCOD = GPIMAC_Altamira.dbo.LPV.LPVEN
		 /*INNER JOIN
		WBCCAD.dbo.INTEGRACAO_ORCCAB WITH (NOLOCK) INNER JOIN
		WBCCAD.dbo.INTEGRACAO_ORCITM WITH (NOLOCK) ON WBCCAD.dbo.INTEGRACAO_ORCCAB.ORCNUM = WBCCAD.dbo.INTEGRACAO_ORCITM.ORCNUM INNER JOIN
		WBCCAD.dbo.INTEGRACAO_ORCPRD WITH (NOLOCK) ON WBCCAD.dbo.INTEGRACAO_ORCITM.ORCNUM = WBCCAD.dbo.INTEGRACAO_ORCPRD.ORCNUM ON 
		GPIMAC_Altamira.dbo.LPV.LPWBCCADORCNUM = WBCCAD.dbo.INTEGRACAO_ORCCAB.ORCNUM*/
	WHERE     
		(GPIMAC_Altamira.dbo.LPV.LPPED = @order)
	FOR XML PATH(''), TYPE).value('.', 'varchar(max)'), 1, 1, '') AS 'order'
GO

GRANT EXECUTE ON MANUFACTURING_BOM TO integracao
