USE [INTEGRACAO]
GO
/****** Object:  User [integracao]    Script Date: 12/11/2014 08:29:57 ******/
CREATE USER [integracao] FOR LOGIN [integracao] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[CM_COLOR]    Script Date: 12/11/2014 08:29:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CM_COLOR](
	[ID] [int] NOT NULL,
	[CODE] [nvarchar](255) NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_CM_COLOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (10, N'GALV-F+PAD', N'GALV-F+PAD')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (11, N'GALV-E+COR', N'GALV-E+COR')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (12, N'S/ PINT', N'S/ PINT')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (13, N'AZ-IR', N'AZ-IR')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (14, N'BEGE-PAD', N'BEGE-PAD')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (15, N'BR-LB', N'BR-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (16, N'GALV-E', N'GALV-E')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (17, N'BG AM-LB', N'BG AM-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (18, N'GALV-F+COR', N'GALV-F+COR')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (19, N'AM-LB', N'AM-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (20, N'CZ-PAD', N'CINZA TEXTURIZADO A PÓ')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (21, N'VD-LB', N'VD-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (22, N'CZ CL-LB', N'CZ CL-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (23, N'BEGE PAD', N'BEGE PAD')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (24, N'AZ-LB', N'AZ-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (25, N'GALV-F', N'GALV-F')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (26, N'GALV-E+PAD', N'GALV-E+PAD')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (27, N'LA-LB', N'LA-LB')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (28, N'PR-LF', N'PR-LF')
INSERT [dbo].[CM_COLOR] ([ID], [CODE], [NAME]) VALUES (29, N'S/ COR', N'S/ COR')
/****** Object:  Table [dbo].[MS_UNIT]    Script Date: 12/11/2014 08:29:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MS_UNIT](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[SYMBOL] [nvarchar](255) NOT NULL,
	[MAGNITUDE] [int] NOT NULL,
 CONSTRAINT [PK_MS_UNIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (104, N'milimetro', N'mm', 1)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (105, N'metro', N'm', 1)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (106, N'quilograma', N'kg', 2)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (107, N'tonelada', N'TON', 2)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (108, N'unidade', N'un', 3)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (109, N'peças', N'pç', 3)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (110, N'minuto', N'min', 4)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (111, N'segundo', N's', 4)
INSERT [dbo].[MS_UNIT] ([ID], [NAME], [SYMBOL], [MAGNITUDE]) VALUES (112, N'hora', N'h', 4)
/****** Object:  Table [dbo].[MS_MAGNITUDE]    Script Date: 12/11/2014 08:29:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MS_MAGNITUDE](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_MS_MAGNITUDE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[MS_MAGNITUDE] ([ID], [NAME]) VALUES (1, N'dimencional')
INSERT [dbo].[MS_MAGNITUDE] ([ID], [NAME]) VALUES (2, N'peso')
INSERT [dbo].[MS_MAGNITUDE] ([ID], [NAME]) VALUES (3, N'unidade')
INSERT [dbo].[MS_MAGNITUDE] ([ID], [NAME]) VALUES (4, N'tempo')

