USE [master]
GO

/****** Object:  Database [INTEGRACAO]    Script Date: 09/19/2014 18:12:51 ******/
CREATE DATABASE [INTEGRACAO] ON  PRIMARY 
( NAME = N'INTEGRACAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\INTEGRACAO.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'INTEGRACAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\INTEGRACAO_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [INTEGRACAO] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INTEGRACAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ARITHABORT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [INTEGRACAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [INTEGRACAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [INTEGRACAO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [INTEGRACAO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [INTEGRACAO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [INTEGRACAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [INTEGRACAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [INTEGRACAO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [INTEGRACAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [INTEGRACAO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [INTEGRACAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [INTEGRACAO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [INTEGRACAO] SET  READ_WRITE 
GO

ALTER DATABASE [INTEGRACAO] SET RECOVERY FULL 
GO

ALTER DATABASE [INTEGRACAO] SET  MULTI_USER 
GO

ALTER DATABASE [INTEGRACAO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [INTEGRACAO] SET DB_CHAINING OFF 
GO



USE [INTEGRACAO]
GO
/****** Object:  User [integracao]    Script Date: 09/19/2014 14:03:58 ******/
CREATE USER [integracao] FOR LOGIN [integracao] WITH DEFAULT_SCHEMA=[dbo]
GO
